AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-slackbolt-openai

  SAM Template for lambda-slackbolt-openai that has the DynamoDB table and Lambda
  functions needed to demonstrate the Websocket protocol on API Gateway.

Parameters:
  # パラメータ：アプリ名
  AppName:
    Type: String
    Default: 'lambda_slackbolt_openai'
    Description: (Required) The name of the new DynamoDB to store connection identifiers for each connected clients. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: 'Required. Can be characters and underscore only. No numbers or special characters allowed.'

Resources:

  # 処理関数
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: lambda.handler
      Runtime: nodejs16.x
      Timeout: 30
      Layers:
        - !Ref AppLayer
      Environment:
        Variables:
          SLACK_SIGNING_SECRET: ""
          SLACK_BOT_TOKEN: ""
          SLACK_APP_TOKEN: ""
          SLACK_BOT_ID: ""
          OPENAPI_SECRET: ""
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  # Layer(共通処理)
  AppLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Base Layer for Node.js
      ContentUri: layers/app-layer/
      RetentionPolicy: Retain
      CompatibleRuntimes:
        - nodejs16.x
    Metadata:
      BuildMethod: makefile

Outputs:

  AppFunctionArn:
    Description: "App function ARN"
    Value: !GetAtt AppFunction.Arn

  ApiURI:
    Description: "API Gateway endpoint URL for Prod stage for AppFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
